name: CI-CD

# When should this workflow run?
on:
  push:
    branches:
      - test

  # Also allows you to start the workflow manually
  workflow_dispatch:

# Permissions given to GitHub Actions
permissions:
  id-token: write
  contents: read

# Common values used throughout the workflow
env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: java-devops
  IMAGE_TAG: latest

jobs:

  # =========================
  # APPLICATION CI
  # =========================
  build-and-push:

    # GitHub gives us a temporary Ubuntu machine
    runs-on: ubuntu-latest

    steps:

      # ==================================
      # STEP 1: Get the code from GitHub
      # ==================================
      - name: Checkout code
        uses: actions/checkout@v4

      # ==================================
      # STEP 2: Install Java 17
      # ==================================
      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      # ==================================
      # STEP 3: Test the Java application
      # ==================================
      - name: Run Maven tests
        run: mvn test

     

      # ==================================
      # STEP 4: Build Docker image
      # ==================================
      - name: Build Docker image
        run: docker build -t java-devops-image .

      # ==================================
      # STEP 5: Scan Docker image
      # ==================================
      - name: Scan Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: java-devops-image:latest
          format: table
          exit-code: '1'
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      # ==================================
      # STEP 6: Connect GitHub Actions to AWS
      # ==================================
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      # ==================================
      # STEP 7: Login to ECR
      # ==================================
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # ==================================
      # STEP 8: Give Docker image its ECR name
      # ==================================
      - name: Tag Docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker tag java-devops-image:latest \
            $REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

      # ==================================
      # STEP 9: Push Docker image to ECR
      # ==================================
      - name: Push Docker image to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push \
            $REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

